### PR TITLE
Update to new gi-crystal and detach libadwaita.cr from gtk4.cr.

### PR DESCRIPTION
**Pull request by hugopl**
Hi;

I ported libadwaita.cr to the newer version of gi-crystal, so now it doesn't need to be a fork of gtk4.cr but just depend on it.

However I noticed that libadwaita.cr plan is to not generate bindings on the fly but have the generated files in the repository, so this patch is probably not a perfect match :sweat_smile: 

Having all files pre-generated have pros and cons

**Pros**
- You know exactly what crystal code you are delivering, no matter if libadwaita releases with a function that breaks gi-crystal tomorrow or not.
- No dependency on gobject-introspection library even at compile-time.

**Cons**
- Git repository with a lot of files not generated or handled by humans
- Possible problems if using libadwaita.cr shard with some other shards that depends on gi-crystal or gtk4.cr, since there'll be duplicated glib/gtk4 bindings in the project.

I prefer generating them on the fly, but this project is not mine :sweat_smile: , so follow your :heart:  and I hope this patch help you somehow.

### CODE REVIEW

**Comment by GeopJr** [comment]
gi-crystal looks awesome, nice work! ☺️

Since libadwaita 1 released I'm fine with generating bindings on the fly (plus I trust your judgement 😅), so I'll move forward with this PR, I just have two concerns(?)/questions:

(P.S. I haven't gone through all gi-crystal changes yet)

- Since the bindings now live in `./lib/gi-crystal/src/auto/`, how are docs going to be generated? I tried symlinking them to `./src/auto/` & moving them (both failed, as expected). Public docs don't really make much sense now that bindings are being generated on the fly (since they might be outdated) but they are helpful offline/manually generated (for context, a github action builds them on commit on this repo and publishes them here: https://libadwaita.geopjr.dev/docs/).
- I noticed that the postinstall script (to generate the bindings) got removed from gtk4.cr, should I add it here or instead add a warning in the readme about the additional step of running `./bin/gi-crystal` manually?

That's all! 😅

**Comment by hugopl** [comment]
I think public docs still make sense, in fact I plan to copy the github action you use to generate the docs here into gtk4 shard :grin: . I just think that probably would be a good idea to say in the docs on what C library version the docs was generated.

Hmmm... good question about doc generation, I didn't test, but I would try two things:

- Generate the bindings under any other directory, just calling `./bin/gi-crystal -o src/auto`
- Call crystal doc under `lib/gi-crystal/src/auto`, but this would miss the project README... maybe we can find a way to tell crystal doc generator to include some file... :thinking: 

Yes, now there's this extra step of calling `gi-crystal`, I tried to run it through a macro and also using a post-install, but failed to make it work without corner cases :disappointed: . Maybe later we can make this happen automagically and a simple `shards build` do everything.

**Comment by hugopl** [comment]
Oops, generate the docs was easier than I thought: https://github.com/hugopl/gtk4.cr/commit/071549ae0f477061a5cc7955eed0c99f72579a92

**Comment by GeopJr** [comment]
Awesome! Thanks for opening this PR, all the info and for your work on gi-crystal! 🙌

**Comment by GeopJr** [comment]
Just a heads-up, since bindings need to be built in the action to generate docs, I made a tiny container with gtk3,4,libadwaita, crystal and others to skip the whole process of installing them in the action (feel free to use):

- https://github.com/GeopJr/libadwaita.cr/pkgs/container/crystal-gtk
- https://github.com/GeopJr/libadwaita.cr/blob/main/Dockerfile
- https://github.com/GeopJr/libadwaita.cr/blob/main/.github/workflows/docs.yml#L11

**Pull request merged**
